- hosts: all
  become: yes
  tasks:
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started

   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: Open the specified ports in the firewall
     firewalld:
       port: "{{ item }}/tcp"
       permanent: yes
       state: enabled
     loop:
       - 6443
       - 2379-2380
       - 10250-10255
       - 30000-32767
        
   - name: Reload firewalld to apply the changes
     service:
       name: firewalld
       state: restarted

   - name: Disable swap by setting swappiness to 0
     sysctl:
      name: vm.swappiness
      value: 0
      state: present

   - name: Deactivate swap
     command: swapoff -a
     ignore_errors: yes  

   - name: Remove swap entry from /etc/fstab
     lineinfile:
       path: /etc/fstab
       regexp: '^/dev/.*swap.*'
       state: absent

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.23.0
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.23.0
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.23.0
        state: present
        allow_downgrade: yes

